nixfiles: jobsets: isos: resolve name conflict
make the iso name a lib.mkForce

error: The option `image.baseName' has conflicting definition values:
- In `/nix/store/081zspnjiwbq85jqhx89gkk2nbyrfg3y-source/nixos/modules/installer/cd-dvd/iso-image.nix': "nixos-graphical-workspace"
- In `/nix/store/081zspnjiwbq85jqhx89gkk2nbyrfg3y-source/nixos/modules/installer/cd-dvd/iso-image.nix': "nixos-nova-nova-25.11pre-git-x86_64-linux"
Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.